[project]
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.30.6",
  "sqlalchemy>=2.0.0",
  "pydantic>=2.7.0",
  "argon2-cffi>=23.1.0",
  "pyjwt>=2.8.0",
  "redis>=5.0.0",
  "httpx>=0.27.0",
]
